############## Education config #################
#################################################
[[education]]
title = "VIT Bhopal University"
timeline = "Ongoing"
description = "I have maintained a solid academic record throughout your studies, excelling in key subjects such as Data Structures, Algorithms, Object-Oriented Programming (OOP), and JavaScript, while also building expertise in full stack development through hands-on projects"

[[education]]
title = "St. Xavier's High School"
timeline = "2019 — 2021"
description = "I pursued a strong academic focus on Physics, Mathematics, and Chemistry. I secured an aggregate percentage of 66.4%, which not only reflects my commitment to academics but also prepared me well for my transition into the technical demands of computer science at the undergraduate level."

[[education]]
title = "St. Xavier's High School"
timeline = "2010 — 2019"
description = "I successfully completed my high school journey at St. Xavier's High School, achieving an aggregate percentage of 72%. This period laid the foundation for who I am today, shaping my core values, work ethic, and passion for learning."


############## Experience config ################
#################################################
[[experience]]
title = "Web designer"
timeline = "2010 — 2013"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Art director"
timeline = "2013 — 2015"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Creative director"
timeline = "2015 — Present"
description = "Nemo enim ipsam voluptatem blanditiis praesentium voluptum delenit atque corrupti, quos dolores et qvuas molestias exceptur."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Web design"
value = "80%"

[[skill]]
title = "Graphic design"
value = "70%"

[[skill]]
title = "Branding"
value = "90%"

[[skill]]
title = "WordPress"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Ingles"
value = "60%"

[[language]]
title = "French"
value = "50%"
